services:
  - type: web
    name: exfit-gym-app
    runtime: docker
    plan: starter
    region: singapore
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: "Exfits Gym"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: local
      - key: LOG_CHANNEL
        value: stderr
      - key: AUTO_MIGRATE
        value: "true"
      - key: MIDTRANS_SERVER_KEY
        sync: false
      - key: MIDTRANS_CLIENT_KEY
        sync: false
      - key: MIDTRANS_MERCHANT_ID
        sync: false
      - key: MIDTRANS_IS_PRODUCTION
        value: "false"
